# fly.toml app configuration file generated for server-late-morning-2173 on 2025-02-17T15:22:29+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-late-morning-2173'
primary_region = 'lax'

[build]

[mounts]
  source = "assets"
  destination = "/assets"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
